# Generated by Django 2.2.5 on 2020-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='foto',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Foto del usuario. Opcional.', null=True, upload_to='miembros/%Y/%m/%d', verbose_name='Foto'),
        ),
    ]
