# Generated by Django 2.2.5 on 2020-05-12 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_docente', models.CharField(max_length=70, unique=True, verbose_name='Categoría Docente')),
            ],
            options={
                'verbose_name': 'Categoría Docente',
                'verbose_name_plural': 'Categorías Docentes',
                'db_table': 'categoria_docente',
                'ordering': ['-categoria_docente'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_especial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_especial', models.CharField(max_length=70, unique=True, verbose_name='Categoría Especial')),
            ],
            options={
                'verbose_name': 'Categoría Especial',
                'verbose_name_plural': 'Categorías Especiales',
                'db_table': 'categoria_especial',
                'ordering': ['-categoria_especial'],
            },
        ),
        migrations.CreateModel(
            name='Categoria_investigador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_investigador', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría de Investigador',
                'verbose_name_plural': 'Categorías de Investigadores',
                'db_table': 'categoria_investigador',
                'ordering': ['categoria_investigador'],
            },
        ),
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=255, unique=True)),
                ('direccion_trabajo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección del centro')),
                ('cargo_ocupa', models.CharField(max_length=255, unique=True)),
                ('telefono_trabajo', models.CharField(max_length=20, verbose_name='Teléfono Trabajo')),
                ('email_trabajo', models.EmailField(blank=True, max_length=254, verbose_name='Email trabajo')),
            ],
            options={
                'verbose_name': 'Datos de centro de trabajo',
                'verbose_name_plural': 'Datos de centros de trabajos',
                'db_table': 'centro_trabajo',
                'ordering': ['-nombre_trabajo'],
            },
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Continente',
                'verbose_name_plural': 'Continentes',
                'db_table': 'continente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidades', models.CharField(max_length=100, verbose_name='Especialidades')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['-especialidades'],
            },
        ),
        migrations.CreateModel(
            name='EspecialidadDoctorado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidaddoc', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad de Doctorado',
                'verbose_name_plural': 'Especialidades de Doctorados',
                'db_table': 'especialidad_doctorado',
                'ordering': ['-nombre_especialidaddoc'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.IntegerField(unique=True, verbose_name='Número del Expediente')),
                ('numero_acuerdo', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expediente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grado_cientifico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_cientifico', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'Grado Científico',
                'verbose_name_plural': 'Grados_científicos',
                'db_table': 'grado_cientifico',
                'ordering': ['-grado_cientifico'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organismo', models.CharField(max_length=255, unique=True)),
                ('cod_organismo', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'db_table': 'organismo',
                'ordering': ['-nombre_organismo'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Continente')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'profesion',
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_tesis', models.CharField(max_length=255, unique=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='tesis/')),
                ('especialidad_doctorado', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.EspecialidadDoctorado')),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesis',
                'db_table': 'tesis',
                'ordering': ['-titulo_tesis'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tutor', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Tutor')),
                ('apellidos_tutor', models.CharField(default='', max_length=50, unique=True)),
                ('email_tutor', models.EmailField(blank=True, max_length=254, verbose_name='Emails')),
                ('telefono_tutor', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('categoria_docente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_docente')),
                ('categoria_especial', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_especial')),
                ('categoria_investigador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_investigador')),
                ('centro_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.CentroTrabajo')),
                ('grado_cientifico', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.Grado_cientifico')),
                ('organismo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Organismo')),
                ('tesis', models.ManyToManyField(related_name='Tesis', to='expediente.Tesis')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutor',
                'ordering': ['-nombre_tutor'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Pais')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Doctorando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(db_index=True, max_length=11, null=True, unique=True, verbose_name='Número de Carné de Identidad')),
                ('pasaporte', models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Número de Pasaporte')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono_fijo', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('movil', models.CharField(max_length=20, null=True, verbose_name='Número de Móvil')),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.IntegerField(choices=[(0, 'Casado'), (1, 'Divorciado'), (2, 'Viudo')])),
                ('categoria_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_docente')),
                ('categoria_especial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_especial')),
                ('categoria_investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_investigador')),
                ('centro_trabajo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.CentroTrabajo')),
                ('continente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.Continente')),
                ('especialidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.Especialidad')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expediente.Expediente')),
                ('grado_cientifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Grado_cientifico')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.Municipio')),
                ('organismo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Organismo')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.Pais')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expediente.Profesion')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.Provincia')),
                ('tesis', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.Tesis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctorando',
                'verbose_name_plural': 'Doctorandos',
                'db_table': 'doctorando',
                'ordering': ['-ci'],
            },
        ),
    ]
