# Generated by Django 2.2.5 on 2020-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorando',
            name='ci',
            field=models.CharField(blank=True, db_index=True, max_length=11, null=True, unique=True, verbose_name='Número de Carné de Identidad'),
        ),
        migrations.AlterField(
            model_name='doctorando',
            name='pasaporte',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Número de Pasaporte'),
        ),
    ]
