# Generated by Django 2.2.5 on 2020-05-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_auto_20200522_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
