# Generated by Django 2.2.5 on 2020-05-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0003_auto_20200522_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centrotrabajo',
            name='cargo_ocupa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='email_trabajo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email trabajo'),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='nombre_trabajo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='centrotrabajo',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Trabajo'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='apellidos_tutor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='nombre_tutor',
            field=models.CharField(max_length=50, verbose_name='Nombre del Tutor'),
        ),
    ]
