# Generated by Django 2.2.5 on 2020-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0004_auto_20200522_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorando',
            name='movil',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Móvil'),
        ),
        migrations.AlterField(
            model_name='doctorando',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
