# Generated by Django 2.2.5 on 2020-05-22 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0005_auto_20200522_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorando',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expediente.Municipio'),
        ),
    ]
