# Generated by Django 2.2.5 on 2020-05-24 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0006_auto_20200522_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorando',
            name='categoria_docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Categoria_docente'),
        ),
        migrations.AlterField(
            model_name='doctorando',
            name='grado_cientifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.Grado_cientifico'),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='cod_organismo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='organismo',
            name='nombre_organismo',
            field=models.CharField(max_length=255),
        ),
    ]
