# Generated by Django 2.2.5 on 2020-06-05 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0007_auto_20200524_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tesis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tesis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='especialidad_doctorado',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.EspecialidadDoctorado'),
        ),
    ]
