# Generated by Django 2.2.5 on 2020-06-07 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0008_auto_20200605_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='especialidad_doctorado',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='expediente.EspecialidadDoctorado'),
        ),
    ]
