# Generated by Django 2.2.5 on 2020-06-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0009_auto_20200607_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidaddoctorado',
            name='nombre_especialidaddoc',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='especialidad_doctorado',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.EspecialidadDoctorado'),
        ),
    ]
