"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
# Para la protección de infromación sensible como los password
# que se almacenen en variables
from decouple import config

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = []

# Application definition
DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'naomi',  # Envío de correo por navegador
    'widget_tweaks',  # Formulario de boostrap
    'sorl.thumbnail',  # Cache imagenes
    'autoslug',  # URL amigables
    'auditlog',  # Log
    'simple_history',  # Log
    'import_export',
    'ckeditor',
    'bootstrap3',
]
LOCAL_APPS = [

]
INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',  # log
    'simple_history.middleware.HistoryRequestMiddleware',  # historial
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Configuracion de CKEDITOR
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
    },
}
# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'America/Havana'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATE_FORMAT = '%d/%m/%Y'
DATE_INPUT_FORMATS = ['%d/%m/%Y']
DECIMAL_SEPARATOR = '.'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    # Comentar cuando se despliegue el proyecto
    os.path.join(BASE_DIR, 'static'),
)
STATIC_FILES = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Thumbnails
# THUMBNAIL_DEBUG = True

# Email settings
# For system testing, use:
# python -m smtpd -n -c DebuggingServer localhost:25

##EMAIL para enviar correo
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
DEFAULT_FROM_EMAIL = 'webmaster@ensap.sld.cu'

##OJO si el proyecto se encuentra en debug mande los correos al navegador sino los envíe por smtp
if DEBUG:
    EMAIL_BACKEND = "naomi.mail.backends.naomi.NaomiBackend"
    EMAIL_FILE_PATH = "G:/Proyectos_Django/ensap/sisdoc/tmp"  # Cambiar en caso de migrar a servidor en linux
##GMAIL
# Para que la aplicación mande mails, por ejemplo a través de GMAIL:
# hay que configurar el gmail que permite quitar la medida de seguridad que impide utilizar programas de terceros para usar el correo
# EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS= True
# EMAIL_PORT= 587
# EMAIL_HOST_USER = 'tu_email_gmail@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu_contraseña_gmail'

# SITE_ID = 1
# DEFAULT_FROM_EMAIL = 'tu_email_gmail@gmail.com'

# ~ EMAIL_HOST = 'ensap.sld.cu'
# ~ EMAIL_PORT = '25'
# ~ SERVER_EMAIL = 'ensap@ensap.sld.cu'
# ~ EMAIL_SUBJECT_PREFIX = '[ENSAP]'
# ~ DEFAULT_FROM_EMAIL = 'ensap@ensap.sld.cu'
# ~ EMAIL_HOST_USER = 'ensap@ensap.sld.cu'
# ~ EMAIL_HOST_PASSWORD = 'admin'
# ~ EMAIL_USE_TLS = True
# ~ EMAIL_IMAP_HOST = 'ensap@ensap.sld.cu'
# ~ EMAIL_IMAP_PORT = '993'
